MODEL:
  nms_size: 10
  nms_thresh: 0.01

  batch_size: 4
  num_epoch: 100

  device: cuda:0
  load_pre_trained_model: false
  pretrained_path: ./save/SuperRetina_Multimodal.pth

  model_save_path: ./save/SuperRetina_Multimodal.pth
  model_save_epoch: 5
  name: "260109_1" # Training experiment name

DATASET:
  model_image_width: 768
  model_image_height: 768
  root_dir: /data/student/Fengjunming/SuperRetina/dataset/FIVES_extract_v2
  registration_type: cffa

PKE:
  pke_start_epoch: 10
  geometric_thresh: 0.7 #3.0 ->0.7
  #content_thresh: 0.8 #越小matches匹配的越严格 0.5->0.8
  content_thresh: 1.0
  gaussian_kernel_size: 21
  gaussian_sigma: 3

  pke_show: true
  pke_show_epoch: 1
  pke_show_list: []

VALUE_MAP:
  area: 8
  value_increase_point: 5
  value_increase_area: 1
  value_decay: 1
  is_value_map_save: false
  value_map_save_dir: ./save/value_maps_tmp
